# Generated by Django 4.2.7 on 2023-11-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('posts', '0001_initial'),
        ('account', '0005_emailaddress_idx_upper_email'),
        ('comments', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('relations', '0001_initial'),
        ('authtoken', '0003_tokenproxy'),
        ('users', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
