# Generated by Django 4.2.7 on 2023-11-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.account'),
        ),
    ]
